try在循环中时，抛出异常10次
循环在try中时，抛出异常1次